
require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*

Layout:
  Exclude:
    - db/seeds.rb
Layout/MultilineMethodCallIndentation:
  Enabled: false
Lint/MissingSuper:
  Exclude:
    - app/services/scrapers/*

Metrics/BlockLength:
  Exclude:
    - config/environments/*
    - config/initializers/*
    - app/services/scrapers/*
Metrics/AbcSize:
  Exclude:
    - app/services/scrapers/*
Metrics/MethodLength:
  Exclude:
    - app/services/scrapers/*

Style:
  Exclude:
    - db/seeds.rb
Style/HashSyntax:
  Enabled: false
Style/Documentation:
  Enabled: false
