development:
  adapter: postgresql
  database: sweeteast_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: sweeteast_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sweeteast_prod
  pool: 5
  timeout: 5000
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
