default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sweeteast_dev

test:
  <<: *default
  database: sweeteast_test
  <% if ENV["CI_TEST"] %>
  adapter: sqlite3
  <% end %>

production:
  <<: *default
  database: sweeteast_prod
