default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sweeteast_dev

test:
  <<: *default
  <% if ENV["CI_TEST"] %>
  database: postgres
  user: postgres
  host: postgres
  password: postgres
  <% else %>
  database: sweeteast_test
  <% end %>

production:
  <<: *default
  database: sweeteast_prod
