name: Rspec Testing
on: [push,pull_request]

jobs:
  # Label of the container job
  ci-testing:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    # Service containers to run with `ci-testing`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Connect to PostgreSQL
      # Runs a script that creates a PostgreSQL client, populates client with data, and retrieves data
      run: node client_pg.js
      # Environment variable used by the `client_pg.js` script to create a new PostgreSQL client.
      env:
        # The hostname used to communicate with the PostgreSQL service container
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
    - name: RSPEC tests
      run: |
        RAILS_ENV=test bin/rails db:create
        RAILS_ENV=test bin/rails db:migrate
        RAILS_ENV=test bundle exec rspec
      env:
        CI_TEST: true

    - name: Yarn Install
      run: yarn install
    - name: Bundle Audit
      run: bundle exec bundle audit check --update
    - name: Run Rubocop
      run: bundle exec rubocop app/
    - name: Run Brakeman
      run: bundle exec brakeman -w1 -z
