name: Rspec Testing
on: [push,pull_request]

jobs:
  # Label of the container job
  ci-testing:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Container job steps
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3
      # Cache Gems (per unique Lockfile) between CI runs!
      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundle-
      # Cache Coverage Reports to Allow Checking of Coverage Loss
      - name: Cache SimpleCov Coverage
        uses: actions/cache@v3
        with:
          path: coverage
          key: coverage

      - name: Bundle Install
        run: |
          gem install bundler
          bundle config --local path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Yarn Install
        run: yarn install
      - name: Bundle Audit
        run: bundle exec bundle audit check --update
      - name: Run Rubocop
        run: bundle exec rubocop app/
      - name: Run Brakeman
        run: bundle exec brakeman -w1 -z
