name: Rspec Testing
on: [push,pull_request]

jobs:
  # Label of the container job
  ci-testing:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rspec

    - name: Yarn Install
      run: yarn install
    - name: Bundle Audit
      run: bundle exec bundle audit check --update
    - name: Run Rubocop
      run: bundle exec rubocop app/
    - name: Run Brakeman
      run: bundle exec brakeman -w1 -z
